export const COUNTRY_CODES = [
    { name: "India", code: "+91", iso: "IN" },
    { name: "United States", code: "+1", iso: "US" },
    { name: "United Kingdom", code: "+44", iso: "GB" },
    { name: "United Arab Emirates", code: "+971", iso: "AE" },
    { name: "Saudi Arabia", code: "+966", iso: "SA" },
    { name: "Canada", code: "+1", iso: "CA" },
    { name: "Australia", code: "+61", iso: "AU" },
    { name: "Singapore", code: "+65", iso: "SG" },
    { name: "Germany", code: "+49", iso: "DE" },
    { name: "France", code: "+33", iso: "FR" },
    { name: "Japan", code: "+81", iso: "JP" },
    { name: "China", code: "+86", iso: "CN" },
    { name: "Russia", code: "+7", iso: "RU" },
    { name: "Brazil", code: "+55", iso: "BR" },
    { name: "South Africa", code: "+27", iso: "ZA" },
    { name: "Nepal", code: "+977", iso: "NP" },
    { name: "Bangladesh", code: "+880", iso: "BD" },
    { name: "Pakistan", code: "+92", iso: "PK" },
    { name: "Sri Lanka", code: "+94", iso: "LK" },
    { name: "Malaysia", code: "+60", iso: "MY" },
    { name: "Ireland", code: "+353", iso: "IE" },
    { name: "New Zealand", code: "+64", iso: "NZ" },
    { name: "Italy", code: "+39", iso: "IT" },
    { name: "Spain", code: "+34", iso: "ES" },
    { name: "Netherlands", code: "+31", iso: "NL" },
    { name: "Switzerland", code: "+41", iso: "CH" },
    { name: "Sweden", code: "+46", iso: "SE" },
    { name: "Norway", code: "+47", iso: "NO" },
    { name: "Denmark", code: "+45", iso: "DK" },
    { name: "Finland", code: "+358", iso: "FI" },
    { name: "Belgium", code: "+32", iso: "BE" },
    { name: "Austria", code: "+43", iso: "AT" },
    { name: "Portugal", code: "+351", iso: "PT" },
    { name: "Greece", code: "+30", iso: "GR" },
    { name: "Turkey", code: "+90", iso: "TR" },
    { name: "Israel", code: "+972", iso: "IL" },
    { name: "Egypt", code: "+20", iso: "EG" },
    { name: "Nigeria", code: "+234", iso: "NG" },
    { name: "Kenya", code: "+254", iso: "KE" },
    { name: "Argentina", code: "+54", iso: "AR" },
    { name: "Chile", code: "+56", iso: "CL" },
    { name: "Colombia", code: "+57", iso: "CO" },
    { name: "Mexico", code: "+52", iso: "MX" },
    { name: "Thailand", code: "+66", iso: "TH" },
    { name: "Vietnam", code: "+84", iso: "VN" },
    { name: "Philippines", code: "+63", iso: "PH" },
    { name: "Indonesia", code: "+62", iso: "ID" },
    { name: "South Korea", code: "+82", iso: "KR" },
].sort((a, b) => a.name.localeCompare(b.name));
